Create is_float() function
thoth-tech/splashkit-core pull request #15
Opened 2022-09-04 07:19 UTC by ZjyChloe

1.Test completed
2.In order to convert columns into other data types, we need to be able to check whether a string is convertible into the desired type. SplashKit already contains boolean functions for checking if a string is an integer or a double. This will be housed within basics.cpp

2022-09-05 11:53 UTC, Alex-MobileApps requested changes
Hi Chloe, at the moment the code isn't compiling because it is missing the `bool is_float(const string &text);` declaration in the basics.h file. Would it be ok if you could add it to the basics.h file, along with a comment above it to match the other methods in the basics.h file? After that I can have a look again.

2022-09-05 17:25 UTC, ZjyChloe commented
I have updated.

2022-09-11 00:36 UTC, Zephreo approved these changes
Compiles and works on my computer
Tested:
- "Test" = False
- "1.2" = True
- "1" = True
- "1.2.3" = False
- "-123.123" = True

2022-09-15 09:32 UTC, Alex-MobileApps approved these changes

2022-09-15 09:33 UTC, merged