Modules/data analytics
thoth-tech/splashkit-core pull request #18
Opened 2022-09-06 13:17 UTC by GaganSinghGit

2022-09-07 07:02 UTC, Zephreo commented on coresdk/src/coresdk/dataframe.cpp
> +            throw std::invalid_argument("Datatype of given element is not the same as datatype of column " + dataframe_get_col_type(df, col_idx));
```suggestion
        if (element_type != DATA_ELEMENT_NULL && element_type != df->col_types[col_idx])
            throw std::invalid_argument("Datatype of given element is not the same as datatype of column " + dataframe_get_col_type(df, col_idx));
        
        df->data[col_idx][row_idx] = data;
```
Unclear throw, you should throw the error first

2022-09-07 07:02 UTC, Zephreo commented on coresdk/src/test/unit_tests/unit_test_dataframe.cpp
> +            REQUIRE( get<int>(extract_col[0]) == 7 );
You should use the method to extract a cell instead of taking the whole column, to set a good example

2022-09-08 04:48 UTC, Alex-MobileApps requested changes
Hi Gaganjeet, I've just noticed in the header file that the `dataframe_update_cell` method is wedged between the operator method (line 260) and its documentation above (lines 242-248). Would you be able to move the operator method's documentation back to the operator method?

I was thinking too that we might want the order of the column and row arguments swapped in the `dataframe_update_cell` method to match the order in the `dataframe_get_cell` method so that it is a bit easier for the user to update and extract elements with the same indexing. We could use `dataframe_update_cell(dataframe &df, int row, int col, data_element &data)` to match the same format. This would mean we could update at (1,2) and then extract at (1,2) instead of needing to remember to switch to (2,1).

Otherwise everything is looking really good and we will be able to merge it after this.

2022-09-15 09:13 UTC, Alex-MobileApps approved these changes

2022-09-15 09:14 UTC, Alex-MobileApps commented
This looks great Gaganjeet. Sorry it took me a while to review this request. I'll merge this now.

2022-09-15 09:14 UTC, merged