Add convert_to_bool and convert_to_char
thoth-tech/splashkit-core pull request #22
Opened 2022-09-19 08:28 UTC by djuggiah

2022-09-20 15:22 UTC, Alex-MobileApps requested changes
Hi Devesh, the code currently isn't compiling at the moment inside the convert_to_char method at the line `std::cout << c`. I have just noticed a few things that might be some small issues. It looks like the method will also print the char instead of returning the char and the convert_to_bool method may not work if there are uppercase letters. Other than that it is looking good so far. Good stuff!

2022-09-20 16:05 UTC, djuggiah commented
Hi Alex, I have updated the code and it's working fine now. Thanks for looking into it.

2022-09-28 03:11 UTC, Alex-MobileApps requested changes
Hi Devesh, it looks like there is a missing semicolon that is stopping the code from compiling. Please see the attached comment with where the line is located.

2022-09-28 03:11 UTC, Alex-MobileApps commented on coresdk/src/coresdk/basics.cpp
> +        return c
It looks like this is the line that is stopping the code from compiling

2022-09-28 06:11 UTC, timmydzeko commented on coresdk/src/coresdk/basics.cpp
> +        return s == "true" || s == "t" || s == "1";
Will this method convert anything that isn't those three terms to False? Do we want a 5 that is put into the convert to bool to return false?

A suggested way to do this is to put the code within an if statement, e.g.
```
{
    if (is_bool(text) {
         // convert to bool body added here
    }
}
```

2022-09-28 06:11 UTC, timmydzeko commented on coresdk/src/coresdk/basics.cpp
> +        return s == "true" || s == "t" || s == "1";
@Alex-MobileApps Is this necessary? Is there a downside to turning everything else into a false value?

2022-09-28 14:19 UTC, djuggiah commented on coresdk/src/coresdk/basics.cpp
> +        return s == "true" || s == "t" || s == "1";
Yes anything else other than these 3, it will out false. Do I still have to include your suggested code?

2023-03-09 01:02 UTC, closed without merging