Collide functions
thoth-tech/splashkit-core pull request #26
Opened 2023-09-04 06:28 UTC by Quackus

Untested, waiting on circle collides test port.

Functions are taken from swingame sgPhysics.pas
Some alteration due to function name changes was done.

use of function is to induce effects for a sprite (with its circle collision) when it has a positive mass value, and detected in collision with another object (Line, Triangle, Rectangle, Circle, Sprite). Only sprite uses mass value for momentum, non-sprites will reflect velocity perpendicular along collision edge.

2023-09-20 14:45 UTC, DaGoblin requested changes
Flagged a few spots with commented-out code, I Think Andrew will reject that.
The Test needs to be added to the test_main.cpp file so test appears on test menu
add_test("Circle Collide Test",run_circle_collide_test);

2023-09-20 14:45 UTC, DaGoblin commented on coresdk/src/coresdk/collides.cpp
> +        //draw_sprite(s);
Based on other reviews this will get picked on, try to avoid comment out code that is not doing anything.

2023-09-20 14:45 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +    //LoadDefaultColors();          //not sure what this does from swingame, seems unused in SK
Just Flagging for me

2023-09-20 14:45 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        //draw_rectangle(COLOR_RED, rect1);     // rect1 is smaller rectangle inside rect
Flaging Turned off code

2023-09-20 14:45 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // rect_pt = closest_point_on_rect_from_circle(temp, r2, rect);
Turned off code

2023-09-20 14:45 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // draw_circle(COLOR_YELLOW, pt_out, 2);
Turned Off Code

2023-09-20 14:45 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // draw_line(COLOR_YELLOW, temp.x, temp.y, temp.x + mouse_out.x, temp.y + mouse_out.y);
Turned Off Code

2023-09-20 14:45 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // yellow line drawn to show vector of mouse position to be moved out of collision
Turned Off Code

2023-09-23 09:34 UTC, DaGoblin approved these changes
Merging with Ours might need to cleanup stray comment before submitting new PR to Top Level Splashkit

2023-09-23 09:34 UTC, merged

2023-09-24 02:33 UTC, Quackus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add CircleCollide Test](https://trello.com/c/goaplsFR/22-add-circlecollide-test)

2023-09-24 02:33 UTC, Quackus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Port swingame "Collides" function group](https://trello.com/c/MAmOnAOD/24-port-swingame-collides-function-group)