Post-porting Collides Alterations
thoth-tech/splashkit-core pull request #27
Opened 2023-09-12 07:32 UTC by Quackus

changes detailed in commit "Collide Alteration".
suggest branch, since it alters source behaviour

post-source porting alteration of collide functions. brief notes
- changed collide_circle_circle
stop sprite from moving through circle, if velocity is perpendicular or facing away from circle
- overload collide_circles
altered calculations, out of collision vector affects both sprite based on mass. momentum change based on in/elastic collisions, 3rd argument elas used to balance the percentage of which type affects end result (inelastic = combine, elastic = trade)
- vector_2d.cpp function vector_angle_between
angle in degrees between the vector lines, not same as angle_between

2023-09-21 01:42 UTC, DaGoblin requested changes
Overall code looks good and clean< i've Flagged code taht's comment out as I think Andrew may reject that. I guess it may have been that way in Swin games?

I am flagging for request changes as I had to add this to the test_main.cpp for the test to appear in the test menu. Unless there's another way to run the test belive it should be added.
add_test("Circle Collide Test",run_circle_collide_test);

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/coresdk/collides.cpp
> +        //draw_line(COLOR_WHITE, line_from(s_center,vector_multiply(centers_vector,10)));
commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/coresdk/collides.cpp
> +            //draw_line(COLOR_WHITE, line_from(s_center,out_vec));
commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/coresdk/collides.cpp
> +            //draw_sprite(s);
commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/coresdk/collides.cpp
> +        int hit_idx;
commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/coresdk/collides.cpp
> +        mvmt = sprite_velocity(s);
commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +    //LoadDefaultColors();          //not sure what this does from swingame, seems unused in SK
Should we Remove it?

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        //draw_rectangle(COLOR_RED, rect1);     // rect1 is smaller rectangle inside rect
Needed for the test?

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +            //-- LineOfLinesCircleHit, Function not in splashkit
Should we remove it?

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // rect_pt = closest_point_on_rect_from_circle(temp, r2, rect);
Commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // draw_circle(COLOR_YELLOW, pt_out, 2);
Commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // draw_line(COLOR_YELLOW, temp.x, temp.y, temp.x + mouse_out.x, temp.y + mouse_out.y);
Commented out code

2023-09-21 01:42 UTC, DaGoblin commented on coresdk/src/test/test_circle_collide.cpp
> +        // yellow line drawn to show vector of mouse position to be moved out of collision
Commented out code

2023-09-21 09:28 UTC, Quackus commented on coresdk/src/test/test_circle_collide.cpp
> +        // rect_pt = closest_point_on_rect_from_circle(temp, r2, rect);
source existant, remove if wanted.

2023-09-21 09:28 UTC, Quackus commented on coresdk/src/test/test_circle_collide.cpp
> +        // draw_circle(COLOR_YELLOW, pt_out, 2);
source existant, remove if wanted.

2023-09-21 09:30 UTC, Quackus commented on coresdk/src/test/test_circle_collide.cpp
> +        // yellow line drawn to show vector of mouse position to be moved out of collision
first two sections were not commented out in source, commented out to distract less. all were in source. remove if wanted

2023-09-21 09:32 UTC, Quackus commented on coresdk/src/test/test_circle_collide.cpp
> +            //-- LineOfLinesCircleHit, Function not in splashkit
this was also commented out in source. you could add this as a future task to implement the function, and see what it does.
otherwise, removing it is fine.

2023-09-21 09:38 UTC, Quackus commented on coresdk/src/coresdk/collides.cpp
> +        mvmt = sprite_velocity(s);
the source code used the commented lines inside of collide circle lines, instead of calling it as someone had the intention to alter its behaviour, based on the bounds boolean parameter.
bounds is currently not utilized, and the commented out section needs to be changed to work (by following the circle_lines design), so calling the function is a substitute.
If bounds parameter is to be neglected in the future, it could be trimmed.

2023-09-21 09:40 UTC, Quackus commented on coresdk/src/coresdk/collides.cpp
> +        int hit_idx;
declaration not necessary, since its not using its own design of circle_lines behaviour. removable if the bounds based parameter alteration to the behaviour isn't planned.

2023-09-21 09:41 UTC, Quackus commented on coresdk/src/coresdk/collides.cpp
> +            //draw_sprite(s);
source existant, remove if wanted.

2023-09-21 09:42 UTC, Quackus commented on coresdk/src/coresdk/collides.cpp
> +            //draw_line(COLOR_WHITE, line_from(s_center,out_vec));
my debug line for observation, removable.

2023-09-21 09:42 UTC, Quackus commented on coresdk/src/coresdk/collides.cpp
> +        //draw_line(COLOR_WHITE, line_from(s_center,vector_multiply(centers_vector,10)));
my debug lines for observing alteration, removable.

2023-09-21 09:42 UTC, Quackus commented on coresdk/src/test/test_circle_collide.cpp
> +    //LoadDefaultColors();          //not sure what this does from swingame, seems unused in SK
since it seems to work without, removing is probably ok.

2023-09-23 09:31 UTC, DaGoblin approved these changes
Perfect

2023-09-23 09:31 UTC, merged

2023-09-24 02:35 UTC, Quackus commented
![](https://github.trello.services/images/mini-trello-icon.png) [Post-porting Collides Alteration](https://trello.com/c/kmxVRjSP/168-post-porting-collides-alteration)