Fix GPIO Tests
thoth-tech/splashkit-core pull request #35
Opened 2024-03-20 00:49 UTC by Liquidscroll

## Description

When the project is compiled from the projects folder, as per CONTRIBUTING.md and then the GPIO tests from `./sktest` are run it results in errors.

These errors are due to a typo in `raspi_gpio.cpp` and an error in the logic of `check_pi()` in `gpio_driver.cpp`.

`check_pi` return true only when `pigpio_start` has returned a negative value, which indicates an error. Thus, its use later on to in `sk_gpio_read` means that pin readings are only attempted on non-compatible boards.

Fixes [#167](https://github.com/splashkit/splashkit-core/issues/167)

## Type of change

- [x]  Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

## How Has This Been Tested?

`sktest` was rerun after the changes, and the tests behave as expected.

## Checklist

- [x]  My code follows the style guidelines of this project
- [x]  I have performed a self-review of my own code
- [x]  My changes generate no new warnings
- [x]  I have requested a review from Aditya Parmar on the Pull Request

2024-03-20 00:49 UTC, Liquidscroll commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix GPIO test errors](https://trello.com/c/ouUwj6Mc/451-fix-gpio-test-errors)

2024-03-20 01:36 UTC, hugglesfox approved these changes
Looks good. Just one small comment

2024-03-20 01:47 UTC, hugglesfox requested changes

2024-03-20 01:47 UTC, hugglesfox commented on coresdk/src/backend/gpio_driver.cpp
>                  if (pi < 0)
The variable pi is only initialized when `sk_gpio_init` is called. Therefore if we try to call `check_pi` before calling `sk_gpio_init` we can't be sure what value it will be. My suggestion would be to set pi to `-1` when it's initialized, that way we can be sure that it'll be less then 0. Then if `sk_gpio_init` succeeds, it'll be set to a value greater then 0 if initialization succeeded or less then 0 on failure (see https://abyz.me.uk/rpi/pigpio/pdif2.html#pigpio_start)

2024-03-20 02:02 UTC, Liquidscroll commented on coresdk/src/backend/gpio_driver.cpp
>                  if (pi < 0)
Yes this would be a good change. This PR concerns itself with getting the tests as they are to run rather than fixing general bugs in the implementation. Do you think this should be done in this PR or should a new issue be created?

2024-03-20 06:11 UTC, hugglesfox commented on coresdk/src/backend/gpio_driver.cpp
>                  if (pi < 0)
I've always been of the opinion that if there's an an bug/problem with the code I'm working with then it's usually best to fix it along with the changes. However I'm happy to accept the PR as is if you don't feel that this is an issue or if you want to split it out into a separate PR.

2024-03-20 06:11 UTC, hugglesfox approved these changes

2024-04-08 10:55 UTC, omckeon approved these changes
Thanks for these fixes!

2024-04-14 09:27 UTC, merged