Interface functionality based on MicroUI - Initial wrapper
thoth-tech/splashkit-core pull request #36
Opened 2024-03-25 05:54 UTC by WhyPenguins

# Description

This PR adds (initial and WIP) interface functionality to SplashKit, by integrating the MicroUI library into the input/rendering code and providing some basic functionality via wrappers.

 - includes MicroUI in the external repository + build process
 - hooks MicroUI into input events (part of `process_events`) and rendering (separate `draw_interface` function)
 - wraps the following functionality:
   - windows (referred to as 'panels')
   - popups
   - labels
   - buttons
 - adds UI test 

Note:
Usage currently requires the loading of a font resource called 'input'. Proper style support will come shortly in another PR that fleshes out the functionality more

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

# How Has This Been Tested?

- Compiled and tested under Windows
- UI test has been run, and functionality such as rendering of windows, and responding to input such as mouse clicks/drags have been observed.
- Keyboard input has also been tested via calls to (currently unwrapped) text input elements. Requires `start_reading_text` to be called beforehand.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
  - I intend to once the API has been mostly settled on
- [x] My changes generate no new warnings
- [ ] I have requested a peer review

2024-03-25 05:54 UTC, WhyPenguins commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add simple initial wrapper of MicroUI](https://trello.com/c/lNjr7ZGf/457-add-simple-initial-wrapper-of-microui)

2024-03-30 04:07 UTC, hugglesfox requested changes
Well done. Just a few questions and suggestions.

2024-03-30 04:07 UTC, hugglesfox commented on coresdk/src/backend/interface_driver.cpp
> +        return text_width((std::string)text, FONT_NAME, FONT_SIZE);
Could the font name and size come from mu_Font? (unfortunately in the mu source it's defined as a void pointer so whether that's possible depends on what it is at runtime)

2024-03-30 04:07 UTC, hugglesfox commented on coresdk/src/backend/interface_driver.h
> +#define FONT_NAME font_named("input")
Should these be here?

2024-03-30 04:07 UTC, hugglesfox commented on coresdk/src/backend/interface_driver_atlas.h
> +void _initialize_atlas_map(){
Could atlas be initialised at compile time?

2024-03-30 04:07 UTC, hugglesfox commented on coresdk/src/backend/interface_driver_atlas.h
> +rectangle atlas[ATLAS_FONT+128];
Should this be static?

2024-03-30 04:07 UTC, hugglesfox commented on coresdk/src/backend/interface_driver_atlas.h
> +static unsigned char atlas_texture[ATLAS_WIDTH * ATLAS_HEIGHT] = {
I'm guessing this is a bin dump of an icon pack? Might be nice to add a comment and cite the source

2024-03-30 04:07 UTC, hugglesfox commented on coresdk/src/coresdk/interface.cpp
> +    }
Add whitespace after the function

2024-03-30 04:07 UTC, hugglesfox commented on coresdk/external
This will also need to be added to the splashkit-external repo

2024-03-30 04:28 UTC, hugglesfox commented on coresdk/src/backend/interface_driver.h
> +#define FONT_NAME font_named("input")
Op sorry just saw the note in the PR description.

2024-03-30 11:54 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +    void _initialize_button_and_key_map()
Indeed, the original C code this is based on (the MicroUI demo) used designated initializers to handle this at compiler time - maybe something similar can be done in C++? Will look into it!

2024-03-30 11:55 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +        if (ctx == nullptr)
Yep sounds good. Just remnants of a previous design I should have removed 😅

2024-03-30 12:04 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +            for(unsigned int i = 0; i < 1/*_sk_num_open_windows*/; i++)
From what I could tell it really _should_ be `_sk_num_open_windows`, but that's static to the graphics driver's unit and there was no way to access it. Have fixed in a later commit where I don't change the SDL_Texture directly.

2024-03-30 12:07 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +                // So create a temporary rgba copy of the data, update the texture, then tidy up.
Definitely an option, but in a later commit I just ended up using `sk_draw_pixel` for each pixel instead, which avoids the allocation and simplifies the logic a bit.

I doubt it's the most efficient way, but to do this properly would require adding another function to the graphics driver, as not all the needed info can be accessed outside of it. Would that be preferred?

2024-03-30 12:12 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +        if (surface)
Wondered the same thing, but most of the code base seems to prefer to log and continue rather than exit (and `to_surface_ptr` informs the user that the surface doesn't exist, so they are aware at least). With that said I can make it assert, what would be preferable here?

2024-03-30 12:13 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +        bool open = mu_begin_window(ctx, name.c_str(), to_mu(initial_rectangle));
Ah this isn't an exception, it's the library returning whether the panel (or 'window') is open or not - they can be closed as well. Same thing for popups.

2024-03-30 12:15 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +        return text_width((std::string)text, FONT_NAME, FONT_SIZE);
Possibly, in fact I was hoping to make this work like that. In later commits I just have two global variables that the user can set with functions, but it would indeed be better as you say. Will give it a go and backport it to this PR too.

2024-03-30 12:16 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver_atlas.h
> +static unsigned char atlas_texture[ATLAS_WIDTH * ATLAS_HEIGHT] = {
Yep, this comes straight from the MicroUI demo. The original file doesn't have attribution info and I forgot to copy it from one of the other files, will fix!

2024-03-30 12:17 UTC, WhyPenguins commented
@hugglesfox Thanks so much for reviewing this! Some of these issues are fixed up in later commits, will try and backport the changes to this PR and fix up the remaining issues as well.

2024-03-31 04:39 UTC, hugglesfox commented on coresdk/src/backend/interface_driver.cpp
> +        const char* alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
> Regarding characters other than Latin1, the rest of SplashKit generally works alright actually, and I've been making patches for the parts that don't quite support it.

Ah sorry. I based that take off the [sk_text_size](https://github.com/thoth-tech/splashkit-core/blob/31b5afa890e4e4db8380d461fc602653ae66990f/coresdk/src/backend/text_driver.cpp#L180-L194) function which uses [TTF_SizeText](https://wiki.libsdl.org/SDL2_ttf/TTF_SizeText) which only supports Latin1. If other areas of the code base support non latin characters then I'll add swapping to [TTF_SizeUTF8](https://wiki.libsdl.org/SDL2_ttf/TTF_SizeUTF8) to the trello board.

Looking into it, the height of the font doesn't depend on the text input. I think it might be a limitation imposed by the splashkit api. We could update the splashkit api to use [TTF_FontHeight](https://wiki.libsdl.org/SDL2_ttf/TTF_FontHeight) for getting the font height which doesn't require the text to be known.

2024-03-31 04:44 UTC, hugglesfox commented on coresdk/src/backend/interface_driver.cpp
> +                // So create a temporary rgba copy of the data, update the texture, then tidy up.
I would have to see the pixel implementation to be sure but my guess is that it would be nicer if we could use a surface, that way the GPU can handle drawing the pixels rather then having to wait for the CPU to feed it a pixel at a time.

Adding a function to the graphics driver sounds like it might be the best option to me?

2024-03-31 04:46 UTC, hugglesfox commented on coresdk/src/backend/interface_driver.cpp
> +        if (surface)
Fair point. My preference is to always use an assert for when the error can only occur if the programmer stuffed up. However as the rest of library simply logs and continues then keeping consistent with that would be the better option.

2024-04-02 08:16 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +                // So create a temporary rgba copy of the data, update the texture, then tidy up.
Sounds good. The original `sk_draw_pixel` implementation is in commit 16fe189c631debe145d819152d921607b872edb6 (took ~55ms) and the improved one is here 76d59e977aef36c4008b71c61057438fc0efc254 (takes ~1ms).

I ended up adding two functions to graphics_driver:
 - `sk_set_bitmap_pixel`, which ensures the `sk_drawing_surface` has a surface we can write to, then writes to it.
 - `sk_refresh_bitmap`, which then replaces the `sk_drawing_surface`'s textures with ones created from that surface.

2024-04-02 08:19 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +        const char* alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Haha I'd already found that issue and added it to the Trello board at the time 🤣 , just need to get around to actually making the PR.
Regarding the height, in commit daffdb41164315c39676671b98196e40785fa48b I added a function to text_driver `sk_text_height` which just calls `TTF_FontHeight` internally, so now this callback uses that.

2024-04-02 08:21 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +        if (ctx == nullptr)
Looking at the other initialization functions in SplashKit, it seems they generally just don't check 😅  I can't find any asserts at all in the SplashKit code base (aside from one of the tests), so just in case there's a reason for that I've opted to just remove the check (in commit 3557972dc3dac287ba73dc57377c70234a679e7a). Seem alright?

2024-04-02 08:22 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +    void _initialize_button_and_key_map()
Looked into it but seems like it isn't that easy. Considering the initialization takes less than a hundredth of a millisecond I didn't want to spend too long on it. Hopefully that's okay 😅

2024-04-02 08:22 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +                    case MU_COMMAND_TEXT: sk_draw_text(surface, FONT_NAME, FONT_SIZE, cmd->text.pos.x, cmd->text.pos.y, cmd->text.str, from_mu(cmd->text.color));break;
Fixed this and other layout issues in c4b04d7b79ab4ac17d0fc7290f5f8e37e369477f -  hopefully alright now!

2024-04-02 08:23 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver.cpp
> +        return text_width((std::string)text, FONT_NAME, FONT_SIZE);
The initial improvement commit for this is 5a2286f9ab93bde233ed47b51013ee31232ee64c, and after that I've made another commit that uses the mu_Font properly (d8e8a33c62a6c028330da82e5a52c409136f6526). Works well, can even change font for just parts of the interface now 😁

2024-04-02 08:26 UTC, WhyPenguins commented on coresdk/src/backend/interface_driver_atlas.h
> +static unsigned char atlas_texture[ATLAS_WIDTH * ATLAS_HEIGHT] = {
Added attribution here - 06f9c6c5d454c023a0f8de614fcb0f99c19dd806

2024-04-02 08:41 UTC, WhyPenguins commented
Alright I think I've addressed all the issues! Hopefully now it's in a bit better shape - let me know if there are any other improvements that can be made 😁

2024-04-02 23:01 UTC, hugglesfox approved these changes
lgtm!

2024-05-03 06:09 UTC, omckeon approved these changes

2024-07-04 14:26 UTC, merged