Update Contibute.md
thoth-tech/splashkit-core pull request #45
Opened 2024-04-14 14:36 UTC by XQuestCode

# Description

This pull request updates the contribution guide to provide clearer instructions and guidelines for contributing to the project. It addresses issue # (insert issue number here).

## Type of change

- [x] Documentation (update or new)

## How Has This Been Tested?

No testing required for documentation changes.

## Testing Checklist

No testing checklist items required for documentation changes.

## Checklist

- [x] My changes adhere to the style guidelines of this project
- [x] I have performed a self-review of my own changes
- [x] I have commented my changes in areas that may be difficult to understand
- [x] I have updated the documentation to reflect the changes made
- [x] My changes do not generate any new warnings
- [x] I have requested a review from a relevant team member on the Pull Request

2024-04-23 11:25 UTC, hugglesfox requested changes
Looks good but I've left a couple of comments where I feel the information could be a little more concise.

2024-04-23 11:25 UTC, hugglesfox commented on CONTRIBUTING.md
> +```
Tools directory isn't in this folder tree despite being mentioned later in the document

2024-04-23 11:25 UTC, hugglesfox commented on CONTRIBUTING.md
> +    └── tools
The tools directory is in the root directory, not inside projects

2024-04-23 11:25 UTC, hugglesfox commented on CONTRIBUTING.md
> +  - `external/`: This directory points to another repository that has libraries that are compiled externally.
More specifically external contains libraries included in the complication as translation units. Additionally it contains headers which are included when building for MacOS

2024-04-23 11:25 UTC, hugglesfox commented on CONTRIBUTING.md
> +  - `lib/`: This directory has all the libraries for each operating system.
lib includes prebuilt libraries to simplify the MacOS and Windows build process.

2024-04-23 11:25 UTC, hugglesfox commented on CONTRIBUTING.md
> +- `generated/`: This directory contains the CMake's translation for the C files.
Not quite. It contains the output of the splashkit translator. These are bindings to splashkit for other languages

2024-04-23 11:25 UTC, hugglesfox commented on CONTRIBUTING.md
> +  - `tools/`:
Might want to consider also mentioning `tools/scripts/cmake`

2024-05-20 09:54 UTC, omckeon commented
@XQuestCode - Just reminding you to check Hayley's comments and update this before Wednesday.

2025-02-28 07:08 UTC, omckeon commented
Closing as not needed

2025-02-28 07:08 UTC, closed without merging