new: add get_system_font() - searches for common system fonts
thoth-tech/splashkit-core pull request #54
Opened 2024-05-14 19:56 UTC by WhyPenguins

# Description

This PR just adds a new function to SplashKit, `get_system_font()`, that can be used to quickly get a nice font. It searches for common fonts across different platforms, and just returns the first one it finds, caching this result so it doesn't have to search upon subsequent calls.

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (update or new)

## How Has This Been Tested?

This has been tested on Windows only, and it can be confirmed that the `meiryo.ttc` font present on my computer is correctly found. Other font names have been verified by checking online, but no verification on a live system has happened - I'd be really grateful if someone set up for this was able to test it across Linux and Mac 😃 

## Testing Checklist

- [x] Tested with sktest (no effect)
- [x] Tested with skunit_tests (no effect)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2024-05-14 20:20 UTC, WhyPenguins commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add function to search for usable system font](https://trello.com/c/WSiBSU3V/602-add-function-to-search-for-usable-system-font)

2024-05-15 05:02 UTC, hugglesfox requested changes
Couple of questions but otherwise looks good.

2024-05-15 05:02 UTC, hugglesfox commented on coresdk/src/coresdk/text.cpp
> +                font result = sk_load_font(file_path.c_str(), 64);
I'm curious as to why `file_path2` and `file_path3` are checked if `file_path` is the only one which ends up being used.

2024-05-15 12:43 UTC, WhyPenguins commented on coresdk/src/coresdk/text.cpp
> +        if (!system_font_attempted_load)
Ah, that's also meant to be static - made a few mistakes when migrating it into this file it seems...

2024-05-15 12:44 UTC, WhyPenguins commented on coresdk/src/coresdk/text.cpp
> +            std::vector<std::string> commonFonts = {
I think this should be okay once `system_font_attempted_load` is static - this logic should only ever run once.

2024-05-15 12:46 UTC, WhyPenguins commented on coresdk/src/coresdk/text.cpp
> +                font result = sk_load_font(file_path.c_str(), 64);
Another embarrassing mistake 😓 - indeed it should be using the path that it actually found the font exists at.

2024-05-19 18:14 UTC, WhyPenguins commented
@hugglesfox Have fixed the logic, and I think the code should be a bit cleaner now too. Thanks if you can take another look, let me know if you spot any more issues!

2024-05-20 10:41 UTC, hugglesfox approved these changes
lgtm!

2024-08-21 08:47 UTC, WhyPenguins commented
Just going to tidy this up since the functionality has been merged upstream 😄 (see [here](https://github.com/splashkit/splashkit-core/pull/176))

2024-08-21 08:47 UTC, closed without merging