feat(gpio): add spi protocol functions
thoth-tech/splashkit-core pull request #56
Opened 2024-05-17 10:13 UTC by Liquidscroll

# Description

This PR adds functions to open and close a connection through SPI, as well as transfer data between devices. This is a common communication protocol and allows us to connect with a wide variety of sensors. Included is a simple test to open a connection, transfer data, and then close.

For more information see tutorial 5 in [this pull reques](https://github.com/thoth-tech/SplashKit-Tutorial/pull/45).

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Included is a test for the basic functionality of the functions, furthermore they have been actively used to produce the tutorial mentioned above. Specifically, they have been used to communicate with the MCP3008 ADC to read a joysticks position. See linked tutorial for more information.

## Testing Checklist

- [x] Tested with sktest
- [x] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2024-05-17 12:27 UTC, hugglesfox requested changes
Looks good, just a couple of comments.

2024-05-17 12:27 UTC, hugglesfox commented on coresdk/src/coresdk/raspi_gpio.cpp
> +    int raspi_spi_transfer(int handle, char *sendBuf, char *recvBuf, int count)
Instead of pointers to chars, would it make more sense to use C++ strings?

2024-05-17 12:27 UTC, hugglesfox commented on coresdk/src/coresdk/raspi_gpio.h
> +     * This function reads the value from the specified pin.
Close reads an input?

2024-05-17 12:27 UTC, hugglesfox commented on coresdk/src/test/test_main.cpp
> +	add_test("GPIO Tests - SPI", run_spi_tests);
indentation

2024-05-20 02:39 UTC, Liquidscroll commented on coresdk/src/coresdk/raspi_gpio.cpp
> +    int raspi_spi_transfer(int handle, char *sendBuf, char *recvBuf, int count)
Not necessarily. The use of strings as buffers has strong opinions both for and against. A lot of developers advocate using a `vector<char>` to explicitly indicate that we're not using text.

Fundamentally, `char` is just storing the bytes that we need to instruct the connected SPI device and to receive the data it sends back. So what we need to send to pigpio is a pointer to a contiguous section of memory and we can get this through 2 ways: C-style arrays (implicit conversion) or passing the return of `.data()` from either an `std::string`, an `std::vector`, or an `std::array`. 

The exact choice depends on what the system that this is used in is actually doing. By implementing this function using pointers we can allow the users themselves to decide on the appropriate container for their use case. The other alternatives are providing overloaded/different functions for each of these containers which might become messy or restricting our users to one or a subset of these containers, neither of which I am a fan of.

2024-05-20 09:16 UTC, hugglesfox approved these changes
Looks good!

2024-05-26 06:24 UTC, omckeon approved these changes
Excellent

2024-05-26 06:24 UTC, merged