feat(gpio): add initial remote gpio work
thoth-tech/splashkit-core pull request #58
Opened 2024-07-28 04:47 UTC by Liquidscroll

# Description

Add functions to support remote GPIO control.

This is a work-in-progress, mainly created at this point to more easily allow the changes to be viewed.

Formatting is pretty scuffed, this will be fixed in the future.

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [ ] Documentation (update or new)

## How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration_

## Testing Checklist

- [ ] Tested with sktest
- [ ] Tested with skunit_tests

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2024-08-06 01:07 UTC, Wills2022 reviewed
Very high quality. I think the test infrastructure you have written is quite robust. 

My comments are mostly me playing devil's advocate and some minor recommendations for formatting adjustments.

2024-08-06 01:07 UTC, Wills2022 commented on coresdk/src/coresdk/raspi_gpio.cpp
> +        return sk_remote_gpio_init(name, host, port);
How do we handle failure of `open_connection()` in `sk_remote_gpio_init()`  if connection to RPI host fails? We return connection object, what happens if connection is dead/malformed?

I would recommend wrapping this in a try-catch or testing whether the connection is "alive" when returned. It might cause erratic behavior in the tests otherwise.

2024-08-06 01:07 UTC, Wills2022 commented on coresdk/src/backend/gpio_driver.cpp
> +			if(!is_connection_open(pi))
Weird indentation.

2024-08-06 01:07 UTC, Wills2022 commented on coresdk/src/test/test_raspi_gpio.cpp
> +
Maybe add a test that tries to send or read from an uninitialized or non-existent port.  Logic in the code accounts for over/underflows  Would be good to verify that the code does not majorly panic if the user does something silly.

2024-08-06 02:31 UTC, Liquidscroll commented on coresdk/src/test/test_raspi_gpio.cpp
> +    connection pi = remote_raspi_init("Raspi", host, 8888);
It's just the default for Pigpio, you have to change this through a flag when you run the daemon (See [here] (https://abyz.me.uk/rpi/pigpio/pigpiod.html) ), so this'll have to be explained in the documentation (unless we change how we do local pigpio functions but thats a whole other conversation...)

2024-08-06 02:33 UTC, Liquidscroll commented on coresdk/src/test/test_raspi_gpio.cpp
> +    cout << "Enter IP Address of remote Pi:\n";
Theoretically, yes. It should resolve it based off the name, not just the IP. The relevant line of code is here: (https://github.com/libsdl-org/SDL_net/blob/22b49f366afbd5963ea9e07d7250d69ad21997f7/src/SDLnet.c#L184C18-L184C31). I say theoretically as I can't get it to work with WSL2, but I think it is WSL2 that has issues with mDNS. I'll test this more when I get a chance to.

2024-08-06 04:19 UTC, Liquidscroll commented on coresdk/src/backend/gpio_driver.cpp
> +                LOG(ERROR) << "Remote GPIO: Connection has UDP Protocol";
AFAIK Pigpio only uses TCP, I swear there's details about this in the documentation somewhere but I can't find it.

I did, however, modify this and tested the UDP functions and I just get back nonsense. I'll need to look into this further about whether it's possible at all, particularly configuring the debug settings for the daemon and seeing what it says when I send a UDP payload.

2024-08-06 04:23 UTC, Liquidscroll commented on coresdk/src/backend/gpio_driver.cpp
> +        connection sk_remote_gpio_init(std::string name, const std::string &host, unsigned short int port)
The RPi 5 completely changed the way we interact with the GPIO pins. We only support the Pigpio Daemon/Library which does not have support for 5+. This is unlikely to change and as far as I can tell there's no libraries that support ALL the RPi 5 functions (e.g. WiringPi still doesn't support PWM on the RPi 5)

2024-08-06 04:24 UTC, Liquidscroll commented on coresdk/src/backend/backend_types.h
> +    // See https://abyz.me.uk/rpi/pigpio/sif.html for more information on these.
Great suggestion! I will include an archive link for the other link too.

2024-08-06 04:29 UTC, Liquidscroll commented on coresdk/src/coresdk/raspi_gpio.cpp
> +        return sk_remote_gpio_init(name, host, port);
Yeah absolutely. To be clear if the connection is not opened the failure is logged in `sk_open_tcp_connection`, in the other functions currently the check for an open connection & immediate return protects from stuff like segmentation faults through accessing nonexistent properties. But yes there can and will be better error handling, I've just held off on that for now because there's going to be a lot of places where we need to check the connection and react appropriately.

2024-08-06 04:32 UTC, Liquidscroll commented on coresdk/src/test/test_raspi_gpio.cpp
> +
Like mentioned in another comment, the errors are logged and exposed to the user and the check for an open connection should prevent anything drastic happening right now -- but I will say there's a number if things to do before this is 'production ready'.

2024-08-08 00:49 UTC, Wills2022 commented on coresdk/src/test/test_raspi_gpio.cpp
> +    connection pi = remote_raspi_init("Raspi", host, 8888);
Ah, that makes sense. I think setting it through the flag is acceptable.  _I don't see any reason not to use that implementation_.

2024-08-08 00:54 UTC, Wills2022 commented on coresdk/src/backend/gpio_driver.cpp
> +        connection sk_remote_gpio_init(std::string name, const std::string &host, unsigned short int port)
That's interesting. I'm surprised that RPI foundation is modifying how GPIO interaction works, but I suppose the current implementation is what, 8+ years old at this point? 

I could see this causing problems as new students use SplashKit. They will probably opt for whatever the newest (or most available)  RPI hardware is, which will be RPI5. 

I think as long as this is documented as a limitation, we should be OK.

2024-08-08 01:01 UTC, Wills2022 commented on coresdk/src/backend/gpio_driver.cpp
> +                LOG(ERROR) << "Remote GPIO: Connection has UDP Protocol";
Rad. It's cool that it's _possible_ but I don't think it's critical that UDP works in the greater context of the pull.  
Like, I assume the reason we favor TCP in this context is because it will actually reliably deliver segments.

2024-08-09 01:54 UTC, hugglesfox requested changes
Looks really good. Just a couple of small comments

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/test/test_raspi_gpio.cpp
>  ***********************************************/
That's not GPL compliant :facepalm:

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/coresdk/raspi_gpio.cpp
> +        }
It might be more apt to call them Power pins. High/Ground are valid states for regular GPIO pins

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/coresdk/raspi_gpio.cpp
> +        return GPIO_DEFAULT_VALUE;
I know splashkit never does error handling but I could see this causing some confusion as the function returns a valid output. I guess this is more of a statement rather then something to fix.

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/backend/gpio_driver.cpp
> +                if(sk_send_bytes(&pi->socket, buffer, num_send_bytes))
I'm wondering why the command is copied to the buffer? E.g. would it be possible to do

```suggestion
                char buffer[num_send_bytes];
                
                if(sk_send_bytes(&pi->socket, cmd, num_send_bytes)) 
```

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/backend/gpio_driver.cpp
> +			cout << "Cleaning Pins on Remote Pi Named: " << pi->name << endl;
```suggestion
		cout << "Cleaning Pins on Remote Pi Named: " << pi->name << endl;
```

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/backend/gpio_driver.cpp
> +
```suggestion
```

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/coresdk/raspi_gpio.cpp
> +            sk_remote_set_pwm_frequency(pi, bcmPin, frequency);
Is it possible for this to fail in the same way as [`gpioSetPWMfrequency`](https://abyz.me.uk/rpi/pigpio/cif.html#gpioSetPWMfrequency)?

If so it would be nice to handle that so the user knows that setting the frequency failed.

(same comment applies to the other pwm functions)

2024-08-09 01:54 UTC, hugglesfox commented on coresdk/src/coresdk/raspi_gpio.h
> +     * @param range  The PWM range to set for the pin.
Might want to specify what the range of acceptable values are (25-40000)

2024-08-09 05:44 UTC, Liquidscroll commented on coresdk/src/coresdk/raspi_gpio.cpp
> +        }
My personal preference would be to call them all lines, but that's not really how it's taught to beginners.

Moving forward I plan to change this across both local and remote functions, as currently I'd like my contributions to match the current local implementation and then improve both at the same time.

2024-08-09 05:47 UTC, Liquidscroll commented on coresdk/src/coresdk/raspi_gpio.cpp
> +        return GPIO_DEFAULT_VALUE;
Yeah, I'd like to change this to some kind of error code with an associated error string.  This matches how the local functions work, so I'd like to change this when I get around to changing the local functions.

2024-08-09 05:58 UTC, Liquidscroll commented on coresdk/src/coresdk/raspi_gpio.cpp
> +            sk_remote_set_pwm_frequency(pi, bcmPin, frequency);
Oh yeah it can. Pretty much every function can fail in some way, including the pre-existing functions. I imagine there'll be a lot of overlap with error handling in both locally and remote.

I was planning to tackle this, and all relevant errors, over the next sprint.

FYI: All possible error codes have defined error messages here: https://github.com/joan2937/pigpio/blob/c33738a320a3e28824af7807edafda440952c05d/command.c#L422

2024-08-09 05:59 UTC, Liquidscroll commented on coresdk/src/test/test_raspi_gpio.cpp
>  ***********************************************/
Sorry not super familiar with this kind of stuff, did you want me to change this to something similar to the rest of the files, i.e.:

```
//
//  test_raspi_gpio.cpp
//  splashkit
//
//  Created by Aditya Parmar on 23/01/2024.
//  Copyright © 2024 Aditya Parmar. All rights reserved.
//
```

If we need to change this to something other than the above, then we'll need to change it across the entire codebase.

2024-08-09 06:27 UTC, Liquidscroll commented on coresdk/src/backend/gpio_driver.cpp
> +                if(sk_send_bytes(&pi->socket, buffer, num_send_bytes))
Nah this doesn't work, what you can do:

`if(sk_send_bytes(&pi->socket, reinterpret_cast<char*>(&cmd), num_send_bytes))`

and then

```
sk_pigpio_cmd_t resp;
int num_bytes_recv = sk_read_bytes(&pi->socket, reinterpret_cast<char*>(&resp), num_send_bytes);
if(num_bytes_recv == num_send_bytes)
{
    return resp.result;
}
```

IMO this is not ideal however, as how the data is interpreted is dependent on the system. Check out the example here: https://en.cppreference.com/w/cpp/language/reinterpret_cast

```
int i = 7;
 
...
 // type aliasing through pointer
char* p2 = reinterpret_cast<char*>(&i);
    std::cout << (p2[0] == '\x7' ? "This system is little-endian\n"
 : "This system is big-endian\n");
```

So, whether that works correctly is dependent on what we run it on.

2024-08-09 12:34 UTC, hugglesfox commented on coresdk/src/test/test_raspi_gpio.cpp
>  ***********************************************/
My bad for not being clearer. The only person who can do something about it is Aditya. Unfortunately his inclusion of all rights reserved means that you're technically breaking the law by editing this file.

2024-08-10 05:19 UTC, hugglesfox commented on coresdk/src/backend/gpio_driver.cpp
> +                if(sk_send_bytes(&pi->socket, buffer, num_send_bytes))
Sh I see because the response of the command is in the command struct. I need to look more into pigio but would splitting the command and the response into seperate structs be possible?

Either way I don't think this needs to block the PR being merged.

2024-08-10 05:24 UTC, hugglesfox commented on coresdk/src/test/test_raspi_gpio.cpp
>  ***********************************************/
Nope. With the GPL it's up to each file to declare its copyright status. For GPL compliance all files must have the following as its possible for a project to have different licences for different files

>     Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Notice how it says that you should've received a copy of the licence? That's what the licence file in the repo is for. It doesn't declare that this project is GPL, is merely a copy of the GPL for reference.

2024-08-10 05:27 UTC, hugglesfox approved these changes
LTGM! Great work on the PR

2024-08-11 00:46 UTC, Wills2022 commented on coresdk/src/test/test_raspi_gpio.cpp
>  ***********************************************/
Oh. That's bad. 
This should probably be reviewed codebase-wide. There are almost certainly other instances where this has occurred, and we're basically hoping the people involved are still involved with the project and are willing to modify the license.

2024-08-11 02:30 UTC, Liquidscroll commented on coresdk/src/test/test_raspi_gpio.cpp
>  ***********************************************/
Yeah look, I don't want to get too deep on this because this is moving into lawyer territory. This subject is not quite as cut and dry as it seems, but I do want to point out some things.

> That's what the licence file in the repo is for. It doesn't declare that this project is GPL...
Right but the SplashKit website explicitly declares that it is covered under GPL:

![image](https://github.com/user-attachments/assets/6bdff2f7-c85a-4c54-99b3-c6732e9fff9e)

This aligns with the FAQ here: https://www.gnu.org/licenses/gpl-faq.en.html#LicenseCopyOnly

"Just putting a copy of the GNU GPL in a file in your repository does not explicitly state that the code in the same repository may be used under the GNU GPL. [...] An explicit statement saying that eliminates all doubt.

[...] The resemblance is not perfect: lawyers and courts might apply common sense and conclude that you must have put the copy of the GNU GPL there because you wanted to license the code that way. Or they might not. Why leave an uncertainty?

This statement should be in each source file. A clear statement in the program's README file is legally sufficient as long as that accompanies the code, but it is easy for them to get separated."

Okay so it seems the explicit statement on the SplashKit website combined with the inclusion of the GPL license file is legally enough to declare SplashKit under GPL. (Note "This statement _should_ be in each source file", not _must_)

Since the SplashKit was covered under GPL when the modifications were made, the GPIO module must also be licensed under GPL, otherwise it is a violation of clause 5.C "c) You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy." (https://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense)

As far as I can tell the only real violation is of clause 5.A "a) The work must carry prominent notices stating that you modified it, and giving a relevant date.", which could be argued that the git history covers this?

2024-08-11 02:35 UTC, Liquidscroll commented on coresdk/src/backend/gpio_driver.cpp
> +                if(sk_send_bytes(&pi->socket, buffer, num_send_bytes))
As far as I can tell, no, but I'll have to dive into the code itself to confirm this.

2024-08-19 08:20 UTC, WhyPenguins commented on coresdk/src/coresdk/raspi_gpio.cpp
> +            cout << "Cant modify a HIGH Pin" << endl;
Wording might be slightly confusing (since the function's for reading rather than writing), perhaps change to 'Cant read a HIGH Pin'? Or better might be to mimic the way the local functions handle these.

2024-08-19 08:35 UTC, WhyPenguins commented on coresdk/src/coresdk/raspi_gpio.cpp
> +        return GPIO_DEFAULT_VALUE;
I think expanding `pin_values` to have a `GPIO_ERROR_VALUE` and returning that could work well? I think that can be returned if a network issue occurs as well.

From what I can tell, the local functions handle the ground/power pins by outputting a default value of high/low (which I think should be adopted here), while errors are undefined behavior since the code just casts whatever `gpio_read` returns to a `pin_value` (including negative error codes😅). Errors really should return an error code I think haha, maybe adding better error handling to the local functions should also be a task.

Also just off topic, but I noticed the local `sk_gpio_read` doesn't return a value if `check_pi` fails, which is also undefined behavior - we should add fixing that as a task too!

2024-08-19 08:36 UTC, WhyPenguins commented on coresdk/src/backend/backend_types.h
> +    } sk_pigpio_cmd_t;
Do you think there'd be any gains in latency/speed if the size of `sk_pigpio_cmd_t` was decreased? I'm just wondering if it could make a difference when continuously polling a pin, for instance.

2024-08-22 21:53 UTC, Liquidscroll commented on coresdk/src/coresdk/raspi_gpio.cpp
> +            cout << "Cant modify a HIGH Pin" << endl;
Hi! Thanks for pointing this out, this has been changed to mimic the local functions.

2024-08-22 21:54 UTC, Liquidscroll commented on coresdk/src/backend/backend_types.h
> +    } sk_pigpio_cmd_t;
I'll definitely look into this but, as per our discussion, my current understanding is that the command struct will be a fraction of what's actually transferred due to the nature of TCP and its handshaking.

2024-09-30 20:13 UTC, WhyPenguins approved these changes
Merging this into a `remote-gpio` branch since its WIP - once it's finished up then that whole set of commits can be sent upstream as a PR. Awesome work again on this!

2024-09-30 20:14 UTC, merged