fix typo documentation
thoth-tech/splashkit-core pull request #62
Opened 2024-08-09 05:07 UTC by DarrenSunandar

# Description

Fix typo in the splashkit website documentation.

## Type of change

- [x] Documentation (update or new)

## How Has This Been Tested?

I find where the typo located and then manage to change from "sqared" to "squared".

## Testing Checklist

- [ ] Tested with sktest
- [ ] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have requested a review from ... on the Pull Request

2024-08-09 07:12 UTC, matt439 commented
This seems to fix the typos in vector_2d.cpp. However when tested on my system, cmake failed to build the library. The issue appears to be that the typo also needs correcting in the vector_2d.h file.  There also seems to be a call of vector_magnitude_sqared in tangent_points in circle_geometry.cpp which will also need updating.

2024-08-09 07:20 UTC, matt439 requested changes
Add name changes to vector_2d.h and circle_geometry.cpp so that they match vector_2d.cpp.

2024-08-10 01:37 UTC, DarrenSunandar commented
I've manage to change the vector_2d.h and circle geometry.cpp file.

2024-08-10 01:50 UTC, matt439 approved these changes
Tested on my system and the library builds successfully. The tests run without issue. Looks good to me.

2024-08-10 10:36 UTC, hugglesfox approved these changes
LGTM

2024-08-26 08:01 UTC, WhyPenguins approved these changes
Nice work, looks good!

2024-09-26 17:15 UTC, merged