Fix bugs in rnd
thoth-tech/splashkit-core pull request #70
Opened 2024-09-02 03:48 UTC by matt439

# Description

The `rnd(int ubound)` and `rnd(int min, int max)` overloads of `rand` generate arithmetic exceptions when a divide by zero occurs through a modulo operator. `rnd(0)` will reliably generate the exception. When `min = max`, the divide by zero will occur in `rnd(int min, int max)` as `... % (max - min)` is used in the function.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I added calls to rnd(0) and rnd(10, 10) to `test_graphics.cpp` to test the edge cases. While it may seem out of place to use `rnd` in `test_graphics.cpp`, `#include "random.h"` was already present in the file with no associated references. Now the `#include` is justified.

## Testing Checklist

- [x] Tested with sktest

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings

2024-09-04 03:35 UTC, Liquidscroll requested changes
Good work! A few issues: 

- What if the user passes in a value for `min` that is greater than `max`? 
- I'm not a fan of the mixing of functionality in the graphics test, this might be better in its own unit test.

EDIT: I just saw PR#68 adds the unit tests for `rnd()`

2024-09-04 03:35 UTC, Liquidscroll commented on coresdk/src/coresdk/random.cpp
> +        if (min == max) return min;
What if min is greater than max? For example running `rnd(50, 10)` returned 56. Should this print an error if this occurs?

2024-09-04 03:35 UTC, Liquidscroll commented on coresdk/src/test/test_graphics.cpp
> +    fill_rectangle_on_bitmap (user_image, COLOR_BLACK, rnd(0), 0, rnd(10, 10), 10);
I don't think this is a great place for this; this should be testing graphics only. The `rnd` functions seem like they'd be a good for unit testing.

2024-09-04 06:12 UTC, matt439 commented on coresdk/src/coresdk/random.cpp
> +        if (min == max) return min;
I added a check for this edge case. I see three potential actions: throw an exception, return 0, or return rnd(max, min). I believe the third option is the best as most people who call rnd(20, 10) are expecting it to behave as rnd(10, 20) anyway. I added an output to the console whenever the function is used improperly. Throwing an exception seems extreme in this case and returning 0 could confuse users.

2024-09-04 06:13 UTC, matt439 commented on coresdk/src/test/test_graphics.cpp
> +    fill_rectangle_on_bitmap (user_image, COLOR_BLACK, rnd(0), 0, rnd(10, 10), 10);
I agree with this. I was concerned that this specific pull request would be deemed insufficient if there was no testing included. I reverted the changes to `test_graphics.cpp`.

2024-09-04 06:51 UTC, Liquidscroll approved these changes
Great job! Left a comment about a clarification that could be made; but I don't think it should block this from the next review.

2024-09-04 06:51 UTC, Liquidscroll commented on coresdk/src/coresdk/random.cpp
> +        if (min == max) return min;
Perhaps adding some form of clarification to this string would be good. Something to let the users know that we'll be swapping the values they've input into the function.

I don't think this should block this from the next review, so I'll approve this.

2024-09-12 01:54 UTC, hugglesfox approved these changes
lgtm

2024-09-12 01:54 UTC, hugglesfox commented on coresdk/src/coresdk/random.cpp
> +        if (min == max) return min;
The correct answer imo would be to throw an error anytime the function is being used incorrectly. However as splashkit is scared of throwing exceptions as they're too scary for people new to programming, I think this is an acceptable way of handling the error.

2024-09-30 19:37 UTC, WhyPenguins requested changes
Looks good! Just would be better to make the `rnd` error be output via the in-built logging system - after that this should be good to merge.

2024-09-30 19:38 UTC, WhyPenguins commented on coresdk/src/coresdk/random.cpp
> +            std::cout << "Error: min value is greater than max value when calling rnd" << std::endl;
Just for consistency this should probably be output via `LOG(WARNING)` rather than `cout`

2024-10-01 00:37 UTC, matt439 commented on coresdk/src/coresdk/random.cpp
> +            std::cout << "Error: min value is greater than max value when calling rnd" << std::endl;
I have altered the output to use LOG(WARNING). It required me to include easylogging++.h in the file.

2024-10-01 10:19 UTC, merged