Fixing bug issue with ipv4_to_str
thoth-tech/splashkit-core pull request #71
Opened 2024-09-07 07:28 UTC by breezy-codes

# Description

When working on some usage examples of network functions I discovered the ipv4_to_str doesn't work how you would assume it would. If you enter an IP address such as 127.0.0.1 it would return 0.0.0.127, so I did some testing and messing around and then tried to see what happens when I entered a decimal, so I did 2130706433 which converted to 127.0.0.1. So really this function is dec_to_ipv4

Fixes # (issue)

ipv4_to_str

## Type of change

I've updated the naming and description, as well as run unit tests to ensure it worked correctly.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Added in tests to the test_networking file, ran convert ipv4 to decimal, as well as decimal to ipv4 to see how they both work together. To ensure the change was correct.
![image](https://github.com/user-attachments/assets/ac4d4a3e-e3bc-4fb7-96fd-f8da89652e0c)

## Testing Checklist

- [x] Tested with sktest - updated the test and added output to check the result
- [x] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from Jonathan on the Pull Request

2024-09-08 05:06 UTC, Liquidscroll approved these changes
This looks good to me! Great work on the new tests, and I particularly like how you went back and ensured that the function was updated across the codebase. I also like how it further reinforces that 'ipv4' refers to the string, human-readable, version of the IP address.

Tests ran as expected on WSL2:
![image](https://github.com/user-attachments/assets/dac3606b-9137-44ad-bf6c-a30c26a4074a)

2024-09-12 02:26 UTC, hugglesfox requested changes
I'm a bit conflicted on this one. On one hand in the context of splashkit's networking code it makes sense for the term ipv4 to refer to the integer representation of it as that's how it's represented in civetweb (the networking library we use). Hence `ipv4_to_str` makes sense if you want to get the string represenation.

However we also have functions such as `ipv4_to_hex` and `ipv4_to_dec` which assume that ipv4 is already a string representation.

Also the tests could probably be unit tests not functional tests.

2024-09-12 06:55 UTC, breezy-codes commented
Hey @hugglesfox, the issue is that if you were to go use it, you would assume its converting from IPv4 to string.
I was trying to make a usage case to show this function but it would return 0.0.0.127, but upon further investigation its because it actually takes a decimal value and converts it into the IPv4 form.
So its actually dec to IPv4.

2025-01-19 00:01 UTC, WhyPenguins commented on .github/pull_request_template.md
> +- [ ] I have requested a review from ... on the Pull Request
This probably isn't meant to be in here? Doesn't seem to be blocking merging, but if you could remove it that'd be better.

2025-01-19 00:07 UTC, WhyPenguins requested changes
The rename makes sense to me! All the other `ipv4_to_...` functions assume the input `ipv4` is a string (making this the odd one out), and considering this does the inverse of `ipv4_to_dec`, then I agree completely with renaming it to `dec_to_ipv4` :smiley: 

Just a couple things to fix up in the PR though, particularly around the tests area. Otherwise looks good!

2025-01-19 00:07 UTC, WhyPenguins commented on coresdk/src/test/test_networking.cpp
> -#define TEST_IP_HEX "0x7F000001"
I don't understand why this hash define was removed, and replaced in the later section - it'd be better to keep this.

2025-01-19 00:07 UTC, WhyPenguins commented on coresdk/src/test/test_networking.cpp
> +    assert(hex_str_to_ipv4("0x7F000001") == TEST_IP);
Just referring to the parts above, it'd be better if these reverted to using the hash define.

2025-01-19 00:07 UTC, WhyPenguins commented on coresdk/src/test/test_networking.cpp
> +    assert(result_ip_2 == test_ip_2);
These should probably just be included in the tests above and written similarly ( a line per test).

2025-02-28 09:43 UTC, merged