Add ability to decode base64 image resources
thoth-tech/splashkit-core pull request #72
Opened 2024-09-12 03:51 UTC by Wills2022

# Description
This change adds the ability for splashkit to decode base64 encoded image files and display them to the screen using existing driver functions. Specifically this enhancement is targeted as a way for users to call the *splashkit* splash screen during program runtime with minimal overhead.

This enhancement was requested in order to give the user the ability to call a function and load a resource without having to specify a file. The benefit of which is that resources can be packaged with the splashkit library files without the need to store resources within the local file structure. The downside of which is that it substantially increases the size of the library if multiple resources are used. 

I will preface that this is a good proof of concept, however I wouldn't actually recommend users use this function. It is reasonable to assume that any user developing a project with SplashKit will have a local file structure for resources, and any splash screen they want to include (SplashKit or otherwise) could just be placed there. 

## Type of change
- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
This has been tested locally on my workstation. I have tested that base64 encoded images are decoded correctly, that invalid base64 images throw the correct errors/logs/exceptions and that this does not trigger any new warnings or break existing drawing functionality.  I have written a small test program to test this out, but it is not included here. It is functionally identical to the "[draw bitmap examples](https://splashkit.io/usage-examples/graphics/#draw-bitmap-examples)" with the calls to `load_bitmap()` and `draw_bitmap()` replaced with `draw_splash_screen()`.

## Testing Checklist
- [X] Tested with sktest
- [X] Tested with skunit_tests

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have requested a review from ... on the Pull Request

2024-09-15 11:04 UTC, matt439 approved these changes
Tested on my system. `draw_splash_screen` correctly drew a tiled image to the screen. Code replication could be resolved but would require significant change to the source code. It is likely best to maintain the duplication in this circumstance due to the fear of creating a new bug which will affect all bitmaps.

2024-09-21 05:49 UTC, Liquidscroll requested changes
There's a few things that I want to discuss further, and I have left comments on these parts.

The code itself  looks good, I've tested the functions on WSL and they work as expected; creating the debug image at the x,y position I've passed to the function.

2024-09-21 05:49 UTC, Liquidscroll commented on coresdk/src/coresdk/images.h
> +     * Draw a pre-defined base64 encoded png file to centre of the the active window
This draws the image to the provided location, not the centre of the screen, right?

2024-09-21 05:49 UTC, Liquidscroll commented on coresdk/src/coresdk/images.cpp
> +        setup_collision_mask(result);
Why are we setting up a collision mask by default for a bitmap? This should be set by the user depending on their needs -- a basic splash screen shouldn't need collision.

2024-09-21 05:49 UTC, Liquidscroll commented on coresdk/src/coresdk/images.cpp
> +    }
This should not be merged while there's a debugging image. 

Could we encode the SplashKit logo with a 3rd-party tool, include that string here and then rename this to `draw_splashkit_splash_screen()`? 
This would also become an example future cohorts to implement encoding and then using this function as a guide to then create a generalised splash screen function.

2024-09-23 01:28 UTC, Wills2022 commented on coresdk/src/coresdk/images.h
> +     * Draw a pre-defined base64 encoded png file to centre of the the active window
Whoops, you're right. Originally I wanted to use the screen_center() function to do this, but that would require including additional splashkit header files into images.cpp

I've changed  the comment on this to reflect what the function actually does.

2024-09-23 02:03 UTC, Wills2022 commented on coresdk/src/coresdk/images.cpp
> +    }
Fair call, I've encoded the actual splashkit  icon and replaced the image string in the code. 
I'd prefer not to rename the function, i feel that `draw_splash_screen()` flows better and the splashkit part is implicit. . If students want to modify the splash screen they would need to modify the SDK. TBH at that point i would assume they would just use `load_bitmap()`. 
![image](https://github.com/user-attachments/assets/2d728392-7f6f-443b-97ce-9e6012775ee2)

2025-02-28 14:29 UTC, merged