Two functions to convert between mac and back
thoth-tech/splashkit-core pull request #79
Opened 2024-11-09 01:00 UTC by breezy-codes

# Description

Developed two new functions. The first converts a MAC address into hexadecimal form, the second converts a hexadecimal value into its MAC address form.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I developed a set of tests to check the mac address conversion was correct. These tests were added into the sktest file and included in this PR for testing. 

![image](https://github.com/user-attachments/assets/16fa6c2b-4b10-4c6e-a012-04aa457fcf6a)
![image](https://github.com/user-attachments/assets/ddc54f66-8a37-4703-989a-6e9b6d9323e1)

## Testing Checklist

- [X] Tested with sktest
- [X] Tested with skunit_tests

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [] I have requested a review from ... on the Pull Request

2024-11-15 08:15 UTC, matt439 requested changes
Tested on WSL. The functions work as intended with properly formatted input strings. I found some possibly unintended behavior by inputting incorrect strings. A validator for the strings could be a possible solution, similar to what you implemented for IP addresses in another PR.

![image](https://github.com/user-attachments/assets/1e82bd5e-57c8-450d-83ba-2fe952ffb35d)

2024-11-17 07:46 UTC, matt439 approved these changes
Tested the `is_valid_max` function and it works as intended. Everything looks great with the pull request.

2025-01-19 04:04 UTC, WhyPenguins reviewed
This is looking good! I think mainly just the tests should be improved, but otherwise it looks well written :smiley:

2025-03-14 08:11 UTC, macite commented
Fixed and merged

2025-03-14 08:11 UTC, closed without merging