Suite of new conversion and maths based functions
thoth-tech/splashkit-core pull request #81
Opened 2024-11-19 03:35 UTC by breezy-codes

# Description

This pull request contains a suite of conversion functions for converting between different values, including input validation for these. In addition to 4 maths based functions.

The added functions are - 
- For input validation - `is_binary`, `is_hex` and `is_octal`
- For conversions -  `dec_to_bin` and back, `hex_to_bin` and back, `oct_to_dec` and back, `hex_to_ct` and back, `base64` encoding and decoding.
- For maths - `calculate_square_root`, `is_prime_number`, `greatest_common_divisor` and `least_common_multiple`.

The motivation for these new functions was based on the addition of some maths and cryptography based tutorials, these are great for converting values for encryption as well as useful in the upcoming steganography tutorials, the maths ones build foundation points for numerous other maths operations and will benefit the maths/cryptography tutorials too.

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

I've done extensive unit checks for checking for both correct and incorrect values as well as edge cases. The unit tests are included in this PR. Some of the unit tests also output when running `sktest` as further validation.

## Testing Checklist

- [X] Tested with sktest
- [X] Tested with skunit_tests

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

![image](https://github.com/user-attachments/assets/24654b79-9918-4d67-b05c-7ddc0f84e5ea)

2024-11-20 07:09 UTC, matt439 requested changes
Everything works very well. I tested the base 64 encoding/decoding with special characters and it handled them flawlessly. The string validity functions also work properly and I was unable to find any edge cases which were not detected. `calculate_square_root` correctly returns `nan` when passing a negative value.

Some minor description changes for some of the functions will help students debug their programs if they are supplying the functions with invalid strings.  I would consider printing warnings to the terminal when invalid strings are used too, so that its even more obvious that they are making a mistake. I tested everything on WSL.

2024-11-25 05:37 UTC, breezy-codes commented on coresdk/src/coresdk/basics.cpp
> +using std::to_string;
It is used in some other files but I'll remove and swap to manually doing it :)

2024-11-25 05:39 UTC, breezy-codes commented on coresdk/src/coresdk/basics.h
> +     * @returns Decimal (unsigned integer) representation of the binary string
Made this change

2024-11-30 02:56 UTC, matt439 approved these changes
The new changes look good and have resolved what I raised in comments.

2025-01-19 04:57 UTC, WhyPenguins reviewed
This looks really comprehensive, nice work! The math functions and base64 conversion parts look great :smiley:  

I do think the conversion functions could be a lot simpler though, which makes me unsure whether to mark as "Approve". I'll leave it as 'Comment' rather than 'Request Changes', since it is a substantial addition and it might be good to include anyway haha.

Main thing for the conversion part is that I feel there's _too_ much work done haha. There were much easier ways to do a lot of this - for instance all of the `**_to_dec` functions could have been basically one-liners that use `stoi` with the base overload like you did in #79; similarly most of the `dec_to_**` could have been done with stringstream (also like in #79). 

Then the other `a_to_b` could all have been one-liners like `return dec_to_b(a_to_dec(str));`, like you have in `hex_to_oct` and `oct_to_hex` :smiley: 

This would substantially reduce the amount of code (and therefore number of potential bugs), so while it's a shame considering how much work was done, I feel like simplifying those functions would be better for the code-base in the long run. It'd also allow negative numbers as a side-effect haha, which right now aren't supported at all.

The tests also really should be in the unit tests (these are the sorts of tests that are perfect for it! :smiley:). I'm not sure why they're in `test_terminal.cpp` to be honest, a new file would have been better.

Overall good work though! In particular I like the base64 implementations, those are pretty nice haha.

2025-01-19 04:57 UTC, WhyPenguins commented on coresdk/src/test/test_terminal.cpp
> +    assert(dec_to_bin(1100) != "11110");
Same as the comment on left on #79, I don't think these negative tests don't really add anything - if the functions are bugged, the likelihood they result in these specific wrong outputs is very low; additionally, many of these were already `assert`ed to be working correctly further up, so if we've reached this point in the code then they _can't_ fail.
This applies to all the other test functions (won't duplicate this message onto them though :rofl:)

2025-01-19 04:57 UTC, WhyPenguins commented on coresdk/src/test/test_terminal.cpp
> +    assert(hex_to_bin("GGGGGG") != "10101011110010");
This applies to all the others like this as well, but if it's testing invalid input that should be handled a specific way (in this case returning an empty string), then _that's_ what should be tested for. There are _millions_ of possible things we don't want it to output, but only one thing we do. `assert(hex_to_bin("GGGGGG") == "");` would be much better.

2025-03-14 08:44 UTC, macite commented
Fixed (some) and merged

2025-03-14 08:44 UTC, closed without merging