Add unit tests and fix bugs for geometry
thoth-tech/splashkit-core pull request #82
Opened 2024-11-20 05:51 UTC by matt439

# Description

There are currently only a handful of unit tests covering geometry methods. A comprehensive set of tests have been added which cover all geometry methods in `circle_geometry`, `geometry`, `line_geometry`, `point_geometry`, `quad_geometry`, `rectangle_geometry`, and `triangle_geometry`; with the exception of those which rely on a window. In the process of creating the tests, I discovered multiple bugs and ambiguous documentation which have been also been rectified.

### Point Method Type Changes
`point_in_triangle` uses `float` for its intermediary calculations. This leads to a loss of precision as `dot_product` operates at `double` precision. All `floats` have been changed to `double`.

### Circle Methods Ambiguous Description
If `closest_point_on_circle` is called when `from_pt` is equal to `c`'s center position, then `c`'s center is returned. This is not made clear in the documentation which only mentions `c`'s circumference. This edge case has been added to the description.

`closest_point_on_rect_from_circle` strictly returns points on the rectangle's perimeter, even if the rectangle encases the circle. This is not made clear in the description so it has been updated to reduce ambiguity.

### Tangent Points Bug Fix.
A bug in `tangent_points` was producing tangent points on the far side of the circle relative to the `from_pt`. This bug has been rectified and now works as intended. I added a real-time graphical test in `sktest`'s geometry suite to more easily appreciate how the function operates.

### Rectangle Type Changes
`rectangle_top`, `rectangle_bottom`, `rectangle_left`, and `rectangle_right` return `float` when the underlying type is `double`. This results in a loss of precision. The functions now return `double`.

### Triangle-Rectangle Intersect Test
I added a real-time graphical test to `sktest`'s geometry suite to check the operation of `triangle_rectangle_intersect`. The function works as intended without any need for changes.

### Set Quad Point Bug Fix
`set_quad_point` incorrectly checks whether `idx` is between the bounds of 0 and 3 and does not allow for points to be altered. The bug has been fixed.

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [x] Documentation (update or new)

## How Has This Been Tested?

Adding the new tests was achieved by running `cmake -G "Unix Makefiles" .` followed by `make` when in the `/splashkit-core/projects/cmake` directory.

## Testing Checklist

- [x] Tested with sktest
- [x] Tested with skunit_tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2024-11-28 06:18 UTC, breezy-codes approved these changes
I've just reviewed this PR.
The updates to the descriptions in the header files are excellent and much more in-depth, good catch on changing those functions from float to double, I'm guessing this was the same issue as there was in sprites being floats.
The updates you've made are thorough, with the values changed from 0 to being 0.0 after changing from float to double, as well as corrected in all the necessary locations.

I've run the unit tests and they work really well to test each of these functions.

2024-11-29 07:12 UTC, NoahJCross approved these changes
I've reviewed this PR and approve these changes. 

### Code Quality & Fixes
- Important precision improvements by converting float to double in `point_in_triangle` calculations to match `dot_product`'s precision
- Fixed critical bug in `tangent_points` that was incorrectly producing points on the far side of circles
- Fixed `set_quad_point` bounds checking issue that prevented point alterations
- Excellent type consistency improvements for rectangle border functions (`rectangle_top`, `rectangle_bottom`, `rectangle_left`, `rectangle_right`) now returning proper double values

### Testing
- Added valuable real-time graphical tests in sktest for:
  - `tangent_points`
  - `triangle_rectangle_intersect`

### Documentation
- Improved clarity around edge cases in `closest_point_on_circle` when point equals circle center
- Better documentation for `closest_point_on_rect_from_circle` regarding perimeter behavior
- Clear explanation of all changes and their rationale

These changes improve both the reliability and precision of the geometry system. The type consistency improvements align well with your other fixes with the sprites, making the overall API more consistent and precise.

2025-01-18 00:47 UTC, WhyPenguins requested changes
Looks good! The bug fixes are great, and I think using `double` more consistently across the codebase is a good idea (there are still a few spots left we should look into switching next). I like the new visualizations too :smiley: 

Just one issue, a few of the unit tests fail for me (and also fail in [CI](https://github.com/splashkit/splashkit-core/actions/runs/12513200643/job/34907512291?pr=196)). 

```C++
/home/activitylist/splashkit-core/coresdk/src/test/unit_tests/unit_test_geometry.cpp:68: FAILED:
  REQUIRE( point_point_distance(point_at(100.0, 100.0), point_at(200.0, 200.0)) == 100.0 * sqrtf(2.0f) )
with expansion:
  141.42136f == 141.421353817
...
/home/activitylist/splashkit-core/coresdk/src/test/unit_tests/unit_test_geometry.cpp:224: FAILED:
REQUIRE( circles_intersect(c5, c7) )
with expansion:
  false
...
/home/activitylist/splashkit-core/coresdk/src/test/unit_tests/unit_test_geometry.cpp:735: FAILED:
  REQUIRE( line_intersects_rect(l, r) )
with expansion:
  false
```

I haven't looked into it too hard, but I suspect it's because of floating point imprecision - some of those tests are using some really tiny epsilon values (and also `point_point_distance` is still using float haha). It'd be useful to look into why they succeeded for you and the other reviewers, perhaps a difference in environment/OS/compiler causes the different floating-point behaviour?

2025-01-21 03:44 UTC, matt439 commented
Thanks for the feedback. The errors occur due to `point_point_distance` returning a float, reducing its precision. The bug is fixed in https://github.com/thoth-tech/splashkit-core/pull/80 which then resolves the failed tests. I was unsure whether to duplicate the bug fix in this PR.

2025-02-25 06:57 UTC, omckeon commented
Closing as this has now been merged upstream

2025-02-25 06:57 UTC, closed without merging