Add bitmap-ray and sprite-ray collision functions
thoth-tech/splashkit-core pull request #85
Opened 2024-12-04 08:11 UTC by matt439

# Description

There has been growing interest in using SplashKit to perform ray-tracing in both 2D and 3D environments. However, there is a lack of ray-based functions, particularly with detecting collisions. I have added bitmap-ray and sprite-ray functions which will allow for much ray-tracing beyond the primitive shapes.

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Added tests

## Testing Checklist

- [x] Tested with sktest

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-12-16 13:08 UTC, NoahJCross requested changes
Nice updates to the circle calculations - using the diagonal distance gives a more precise radius than the previous MAX approach. Other than needing the INVALID_PTR check in bitmap_ray_collision, everything else looks good to go.

2024-12-16 13:08 UTC, NoahJCross commented on coresdk/src/coresdk/collisions.cpp
> +    {
This should check for an invalid ptr to the bitmap

2024-12-16 21:00 UTC, matt439 commented
Added a check for invalid bitmap pointer in `bitmap_ray_collision`.

2024-12-17 13:33 UTC, NoahJCross approved these changes
I've reviewed this PR and approve of these changes.
The ray collision functions add important features to SplashKit while keeping high standards:
# Code Quality
Good use of matrix transformations for bitmap calculations
Proper collision detection with bitmap pixels
Good handling of edge cases (null checks, out of bounds)
Clean code that fits well with existing collision systems
# Testing
Good test coverage in test_geometry.cpp
# Documentation
Clear methods for both bitmap and sprite collision checks
Consistent design with other collision functions
Well-documented code that explains the parameters

The changes add useful collision features while keeping types consistent and calculations accurate.

2025-01-18 22:58 UTC, WhyPenguins approved these changes
Looks good! I think implementing the ray collision via a new general case `bitmap_quad_collision` was a good choice. I think the only downside might be inefficiency when the ray is diagonal (I believe it has to check the entire sprite at that point?).

Tests look good and it works well! Nice work!

Just leaving a note here for anyone looking, future work could be to write a more special case ray-intersection function that might be quicker (probably via DDA raymarching), and also returning the hit point/distance. In the current setup I think this could be found by updating the hit point/distance inside the `_step_through_pixels` lambda, before returning the result.

2025-01-21 04:31 UTC, matt439 commented
Thanks for the feedback. Yes the edge case when the ray's heading matches the division between the triangles is a problem. Hopefully it does not occur too often but an improved solution would be a good task for next trimester.

2025-02-02 08:57 UTC, merged