fixed replace all error (newText -> new_text)
thoth-tech/splashkit-core pull request #86
Opened 2024-12-06 01:17 UTC by ctrlvish

# Description

In python there is an error when trying to use replace_all.
File "/home/breezy/.splashkit/python3/splashkit.py", line 4098, in replace_all
    __skparam__newText = __skadapter__to_sklib_string(newtext)
                                                      ^^^^^^^
NameError: name 'newtext' is not defined. Did you mean: 'newText'?

In order to fix this, the parameter newText needs to be changed to snake case instead of camel case to suit c++ naming conventions. `newText` -> `new_text`

Fixes # (issue)

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

I tested this on my local `splashkit.py` file by changing the relevant parameter and doing `skm global install`, then running a simple python code to test the `replace_all` function.

change made from `newText` to `new_text` on my local `splashkit.py`:
<img width="694" alt="image" src="https://github.com/user-attachments/assets/aaaef934-7896-49a4-985c-c4bc84d62082">

program running with no errors:
<img width="699" alt="image" src="https://github.com/user-attachments/assets/bc66b805-9b15-49d9-bcc9-a8688813ffa7">

`new_text` parameter:
<img width="513" alt="image" src="https://github.com/user-attachments/assets/01453d8e-3381-4ca3-80a8-c330fafbfbec">

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-12-07 00:57 UTC, matt439 requested changes
The error has bee resolved by renaming the parameters. Tested on WSL and it works as intended. However, most of the changes in this PR appear to be attempting to improve the formatting of the files. While I agree that SplashKit's source code has questionable style choices, this is not the place to fix them. A separate PR should be made with the formatting changes so that there is a separation between the motivations.

2024-12-07 00:57 UTC, matt439 commented on coresdk/src/coresdk/basics.cpp
> +        s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](int c)
Is this purely a formatting change?

2024-12-07 00:57 UTC, matt439 commented on coresdk/src/coresdk/basics.cpp
> +        s.erase(std::find_if(s.rbegin(), s.rend(), [](int c)
Formatting?

2024-12-07 00:57 UTC, matt439 commented on coresdk/src/coresdk/basics.cpp
> +        if (s.empty() || ((!isdigit(s[0])) && (s[0] != '-') && (s[0] != '+')))
Formatting?

2024-12-07 00:57 UTC, matt439 commented on coresdk/src/coresdk/basics.cpp
> +        char *p;
Formatting?

2024-12-07 00:57 UTC, matt439 commented on coresdk/src/coresdk/basics.cpp
> +        return std::stoi(text);
Formatting?

2024-12-07 00:57 UTC, matt439 commented on coresdk/src/coresdk/basics.cpp
> +        return std::stod(text);
Formatting?

2024-12-07 00:57 UTC, matt439 commented on coresdk/src/coresdk/basics.h
There are many small changes in this file too. Are they also purely to improve formatting?

2024-12-07 04:14 UTC, ctrlvish commented on coresdk/src/coresdk/basics.cpp
> +        s.erase(s.begin(), std::find_if(s.begin(), s.end(), [](int c)
Hi @matt439,
My VS Code had made these formatting changes, thanks for pointing it out! I've undid the changes now and you may re-review it.

2024-12-07 05:45 UTC, matt439 requested changes
All of the issues with the formatting changes have now been fixed. However, there are now changes to README.md which seem unnecessary.

2024-12-07 05:45 UTC, matt439 commented on README.md
This file seems to have some strange changes.

2024-12-08 01:50 UTC, ctrlvish commented on README.md
Hi @matt439 , this was due to a PR being merged upstream. I've done a rebase and it should be okay now if you check the Files changes tab.

2024-12-08 06:16 UTC, matt439 approved these changes
All looks good now.

2024-12-20 13:16 UTC, NoahJCross approved these changes
I’ve tested it, and everything looks good.

2025-02-02 08:17 UTC, omckeon approved these changes

2025-02-02 08:20 UTC, merged